export const CHECKBOXES_CHANGE = "CHECKBOXES_CHANGE";

export const SELECTED_CHECKBOXES = "SELECTED_CHECKBOXES";

export const UPDATE_CLOSE_COCKTAIL = "UPDATE_CLOSE_COCKTAIL";

export const UPDATE_POSSIBLE_COCKTAIL = "UPDATE_POSSIBLE_COCKTAIL";

export const CLOSE_GREETING_MESSAGE = "CLOSE_GREETING_MESSAGE";

export const OPEN_GREETING_MESSAGE = "OPEN_GREETING_MESSAGE";

export const RESET = "RESET";